version: "3.3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5243:5243"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:5243"]
      timeout: 10s
      retries: 20
volumes:
  db:
    driver: local
